version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cliptagger-backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/data:/usr/src/app/data
    ports:
      - "5000:5000"
    networks:
      - cliptagger-network

  frontend:
    build: ./frontend
    container_name: cliptagger-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - cliptagger-network

networks:
  cliptagger-network:
    driver: bridge
