version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cliptagger-backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/data:/usr/src/app/data
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/clips"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - cliptagger-network

  frontend:
    build: ./frontend
    container_name: cliptagger-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - cliptagger-network

networks:
  cliptagger-network:
    driver: bridge
